# -*- coding: utf-8 -*-
"""ex006

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXkYwjBqIsUn9oESsnMBOWE1pWp7zS1W
"""

num = int(input("Digite um número: "))
dobro = num*2
triplo = num*3
raiz = num ** 0.5
print("O dobro de {} é {}.".format(num, dobro))
print("O triplo de {} é {}\nE a raíz quadrada de {} é {:.2f}".format(num, triplo, num, raiz))