# -*- coding: utf-8 -*-
"""ex005

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4_Cj6PxVSzB9jVFPGXT65DSdMMN0yk0
"""

num = int(input("Digite um número: "))


print("O número digitado foi {}, seu antecessor é {} e seu sucessor é {}".format(num, (num-1), (num + 1)))