# -*- coding: utf-8 -*-
"""ex007

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_28ULyEpkFwWsUQkFdHF6I5PmqkXzKY
"""

print("=== Escola Capivara ===")

nome = input("Digite o nome do aluno: ")
n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))

media = (n1 + n2) / 2

print ("A média do aluno {} é de {}".format(nome, media))