# -*- coding: utf-8 -*-
"""ex004

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8amKP_NB2aSSh5Rqg-j37Np-Hxemrsn
"""

a = input("Digite algo: ")
print("o tipo primitivo é ", type(a))
print("É um número? ", a.isnumeric())
print("É alfabético? ", a.isalpha())
print("É alfanumérico? ", a.isalnum())
print("Tem espaços? ", a.isspace())
print("Está em maiúsculo? ", a.isupper())
print("Está em minúsculo? ", a.islower())
print("Está capitalizada? ", a.istitle())