# -*- coding: utf-8 -*-
"""ex003

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yr26Qox5AaLRDf8JthFHU_MxaYY1rf58
"""

a = int(input("Digite um número: "))
b = int(input("Digite outro número: "))
soma = a + b

print("A soma de {} e {} é igual a {}".format(a, b, soma))