# -*- coding: utf-8 -*-
"""ex009

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6Pmfdn_9f_p32tOzNooNG5iLglwk5Ns
"""

print ("xxx Tabuada xxx")

numero = int(input("Digite um número para saber sua tabuada: "))

print("{} x {} = {}".format(numero, 1, (numero * 1)))
print("{} x {} = {}".format(numero, 2, (numero * 2)))
print("{} x {} = {}".format(numero, 3, (numero * 3)))
print("{} x {} = {}".format(numero, 4, (numero * 5)))
print("{} x {} = {}".format(numero, 6, (numero * 6)))
print("{} x {} = {}".format(numero, 7, (numero * 7)))
print("{} x {} = {}".format(numero, 8, (numero * 8)))
print("{} x {} = {}".format(numero, 9, (numero * 9)))
print("{} x {} = {}".format(numero, 10, (numero * 10)))