# -*- coding: utf-8 -*-
"""ex008

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jENOKCPbi4D-tfHkPgwVZ2J2Dvuc2R5T
"""

print("=== Conversor de medidas ===")

medida = float(input("Digite a medida em metros: "))

centimetros = medida * 100

milimetros = medida * 1000

print("{} metros é igual a {} centímetros ou {} milimetros".format(medida, centimetros, milimetros))