# -*- coding: utf-8 -*-
"""ex014

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfCm8HNEiNmo7KoBo3AJ1fPNssgGP39s
"""

print("=== Conversor de temperatura ===")
print("Escreva um programa que converta uma temperatura digitando em graus Celsius e converta para graus Fahrenheit.\n\n\n")

temperatura = float(input("Digite a temperatura em graus Celsius: "))

fahrenheit = (temperatura * 9 / 5) + 32

print("{}° Celsius correspondem a {}° Fahrenheit".format(temperatura, fahrenheit))