# -*- coding: utf-8 -*-
"""ex013

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rVhKVQ3U37Kpngl5-aiPITYRzzJlhE0
"""

print("--- Reajuste Salarial ---")
print("Faça um algoritmo que leia o salário de um funcionário e mostre seu novo salário, com 15% de aumento.\n\n\n")

salario = float(input("Digite seu salário: R$"))

reajuste = salario + (salario*0.15)

print("Seu salário de R${} agora passa a ser R${:.2f}".format(salario, reajuste))