# -*- coding: utf-8 -*-
"""ex012

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsQ7ore6jvimey-4SEUdm-1YnweWUL-Z
"""

print("---Calculando descontos---")
print("Faça um algoritmo que leia o preço de um produto e mostre seu novo preço, com 5% de desconto.\n\n\n")

produto = input("Digite o produto: ")
preco = float(input("Digite seu valor: R$"))

desconto = preco - (preco * 0.05)


print("O {} de valor R${} com o desconto de 5% fica no valor de R${:.2f}".format(produto, preco, desconto))