# -*- coding: utf-8 -*-
"""ex015

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTn12ejB3tPZnOdDAqahbzCjpUHgbPUY
"""

print("=== Aluguel de carros ===")
print("""Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado
e a quantidade de dias pelos quais ele foi alugado. Calcule o preço a pagar,
sabendo que o carro custa R$60 por dia e R$0,15 por Km rodado.\n\n\n""")

dias = int(input("Por quantos dias o carro foi alugado? "))
km = float(input("Quantos quilômetros foram rodados? "))


valor_total = (dias * 60) + (km * 0.15)

print("O carro ficou {} dias alugado e rodou {}km, ficando em um total de R${:.2f}".format(dias, km, valor_total))