# -*- coding: utf-8 -*-
"""ex011

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11i-J7pveVBBBqSwJrdtsVWXHYLq9Rt5U
"""

print("--- Cálculo de parede ---")

print("""Faça um programa que leia a largura e a altura de uma parede em metros,
calcule a sua área e a quantidade de tinta necessária para pintá-la,
sabendo que cada litro de tinta pinta uma área de 2 metros quadrados.\n\n\n""")

altura = float(input("Digite a altura do muro em metros: "))
largura = float(input("Dgite a largura do muro em metros: "))

area = altura * largura

tinta = area / 2

print("O muro tem {}m² e serão necessários {:.2f} litros de tinta".format(area, tinta))