# -*- coding: utf-8 -*-
"""ex010

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBYWE8mEobfSz83TSBiiOz3ziGwE9Rjv
"""

print("---Conversor de moedas---")

carteira = float(input("Digite o valor em reais que voce tem na carteira: R$"))

dolar = carteira / 5.41

print("Com R${} você consegue comprar U${:.2f}".format(carteira, dolar))