# -*- coding: utf-8 -*-
"""ex028

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQ1wpX4G4JpWmtXMW7oxLvKcc916sqlC
"""

import random
print("Jogo da Adivinhação")
print("""Escreva um programa que faça o computador “pensar” em um número inteiro entre 0 e 5
e peça para o usuário tentar descobrir qual foi o número escolhido pelo computador.
O programa deverá escrever na tela se o usuário venceu ou perdeu. \n\n\n""")

lista = [0, 1, 2, 3, 4, 5]
jogador = int(input("Escolha um número de 0 a 5: "))
computador = random.choice(lista)

if jogador == computador:
    print(f'Jogador escolheu {jogador} e o computador escolheu {computador}')
    print("Você ganhou!")
else:
    print(f'Jogador escolheu {jogador} e o computador escolheu {computador}')
    print("Você perdeu!")