# -*- coding: utf-8 -*-
"""ex029

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tS6P82GjUTIi8qSPUQ572Tw9MDwM1_e
"""

print("=-=-= Radar de Velocidade =-=-=")
print('''Escreva um programa que leia a velocidade de um carro.
Se ele ultrapassar 80Km/h, mostre uma mensagem dizendo que ele foi multado.
A multa vai custar R$7,00 por cada Km acima do limite.\n\n\n''')

velocidade = int(input("Qual a velocidade do carro? "))
multa = 0

if velocidade > 80:
  multa = (velocidade - 80) * 7
  print(f"Você foi multado em R${multa:.2f}!")
else:
  print("Você não foi multado!")