# -*- coding: utf-8 -*-
"""ex033

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBRjgyBoUFENj4q1vWTUZbuQ_kbvFLbp
"""

print("=-=-= Maior e menor valor =-=-=-")
print('''Faça um programa que leia três números
e mostre qual é o maior e qual é o menor.\n\n\n''')

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
num3 = int(input("Digite o terceiro número: "))

maior = 0
menor = 0
#verificando o maior
if num1 > num2 and num1 > num3:
  maior = num1
  print(f'O maior número é {maior}')

elif num2 > num1 and num2 > num3:
  maior = num2
  print(f'O maior número é {maior}')

else:
  maior = num3
  print(f'O maior número é {maior}')

#verificando o menor
if num1 < num2 and num1 < num3:
  menor = num1
  print(f'O menor número é {menor}')

elif num2 < num1 and num2 < num3:
  menor = num2
  print(f'O menor número é {menor}')

else:
  menor = num3
  print(f'O menor número é {menor}')