# -*- coding: utf-8 -*-
"""ex032

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1troc0fXOxqFky34ntDMFfdN5UA7Ajf4b
"""

print("=-=-= Ano Bissexto =-=-=")
print(''' Faça um programa que leia um ano qualquer e mostre se ele é bissexto.\n\n\n''')

ano = int(input("Digite um ano para saber se ele é bissexto: "))

if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
  print(f"O ano {ano} é bissexto!")
else:
  print(f"O ano {ano} não é bissexto")