# -*- coding: utf-8 -*-
"""ex030

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1086bbCzpw842EL5MnGeoZ3nQSVsH1SXP
"""

print("=-=-= Par ou Ímpar =-=-=")
print('''Crie um programa que leia um número inteiro e mostre na tela se ele é PAR ou ÍMPAR.\n\n\n''')

num = int(input("Digite um número inteiro: "))
if num % 2 == 0:
    print(f"O número {num} é PAR!")
else:
    print(f"O número {num} é ÍMPAR!")