# -*- coding: utf-8 -*-
"""ex034

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1K1upBVN2_2gdcNQn55s0341wzAuUxo
"""

print("=-=-= Aumentos Múltiplos =-=-=")
print('''Escreva um programa que pergunte o salário de um funcionário e calcule o valor do seu aumento.
Para salários superiores a R$1250,00, calcule um aumento de 10%.
Para os inferiores ou iguais, o aumento é de 15%.\n\n\n''')

salário = float(input('Qual é o salário do funcionário? R$'))

if salário <= 1250:
    novo = salário + (salário * 15 / 100)
    print(f'Seu salário com aumento de 15% é de R${novo:.2f}')
else:
  novo = salário + (salário * 10 / 100)
  print(f'Seu salário com aumento de 10% é de R${novo:.2f}')