# -*- coding: utf-8 -*-
"""ex031

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103BbkPPRJDcY6cc_sot92YZWDMlsycMj
"""

print("=-=-= Custo da viagem =-=-=")
print('''Desenvolva um programa que pergunte a distância de uma viagem em Km.
Calcule o preço da passagem, cobrando R$0,50 por Km para viagens de até 200Km
e R$0,45 parta viagens mais longas.\n\n\n''')

viagem = float(input("Quantos km você quer percorrer? "))

if viagem > 200:
  custo = viagem * 0.45
  print(f'Sua passagem custará R${custo:.2f}!')
  print('Boa viagem!')
else:
  custo = viagem * 0.50
  print(f'Sua passagem custará R${custo:.2f}!')
  print('Boa viagem!')

  #If/Else ternário
  #custo = viagem * 0.45 if viagem > 200 else viagem * 0.50