# -*- coding: utf-8 -*-
"""ex094.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TaHdw5EAFGGBmP6SwiDxweYs33pxnHP
"""





'''
Crie um programa que leia nome, sexo e idade de várias pessoas,
guardando os dados de cada pessoa em um dicionário e todos os dicionários
 em uma lista. No final, mostre:
 A) Quantas pessoas foram cadastradas
 B) A média de idade
 C) Uma lista com as mulheres
 D) Uma lista de pessoas com idade acima da média
'''

print('='*30)
print(f"{'Cadastro de Pessoas':^30}")
print('='*30)
print('\n\n\n')

galera = []
pessoa = {}
soma = 0
while True:
  pessoa['nome'] = str(input('Nome: '))
  while True:
    pessoa['sexo'] = str(input('Sexo: [M/F]')).upper().strip()[0]
    if pessoa['sexo'] in 'MF':
      break
    print('ERRO! Por favor, digite apenas M ou F.')
  pessoa['idade'] = int(input('Idade: '))
  soma += pessoa['idade']
  galera.append(pessoa.copy())
  while True:
    resposta = str(input('Quer continuar? [S/N]')).upper().strip()[0]
    print('--'*30)
    if resposta in 'SN':
      break
    print('ERRO! Responda apenas S ou N.')
  if resposta == 'N':
    break

print('-=' * 30)
print(f'A) Ao todo temos {len(galera)} pessoas cadastradas.')
media = soma / len(galera)
print(f'B) A média de idade é de {media:5.2f} anos.')
print(f'C) As mulheres cadastradas foram ', end='')
for p in galera:
  if p['sexo'] in 'Ff':
    print(f'{p["nome"]} ', end='')
print()
print(f'D) Lista das pessoas que estão acima da média:', end='')
for p in galera:
  if p['idade'] >= media:
    print('     ')
    for k, v in p.items():
      print(f'{k} = {v}; ', end='')
    print()
print(' ===  FIM === ')

