# -*- coding: utf-8 -*-
"""ex095.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJkhA12O-q0vN8O8TCCfwKqy9w8R0EVl
"""

'''
Aprimore o desafio 93 para que ele funcione com vários jogadores,
incluindo um sistema de visualização de detalhes do aproveitamento
de cada jogador.
'''
print('='*30)
print(f"{'Aprimorando os dicionários':^30}")
print('='*30)
print('\n\n\n')

time = []
jogador = {}
partidas = []

#alimentando os dados
while True:
  jogador.clear()
  jogador['nome'] = str(input('Nome do jogador: '))
  total = int(input(f"Quantas partidas {jogador['nome']} jogou? "))
  partidas.clear()
  for c in range(0, total):
      partidas.append(int(input(f"Quantos gols na partida {c+1}? ")))
  print('\n\n\n')
  jogador['gols'] = partidas[:]
  jogador['total'] = sum(partidas)
  time.append(jogador.copy())
  while True:
    resposta = str(input('Quer continuar? [S/N] ')).upper()[0]
    if resposta in 'SN':
      break
    print('ERRO! Responda apenas S ou N.')
  if resposta == 'N':
    break

#cabeçalho
print('-='*30)
print('cod ', end='')
for i in jogador.keys():
  print(f'{i:<15}', end='')
print()

#dados tabulados
print('--'*30)
for k, v in enumerate(time):
  print(f'{k:>3}', end=' ')
  for d in v.values():
    print(f'{str(d):<15}', end='')
  print()
print('--'*30)

#Busca de dados
while True:
  busca = int(input('Mostrar dados de qual jogador? (999 para parar) '))
  if busca == 999:
    break
  if busca >= len(time):
    print(f'ERRO! Não existe jogador com código {busca}!')
  else:
    print(f'-- LEVANTAMENTO DO JOGADOR {time[busca]["nome"]}:')
    for i, g in enumerate(time[busca]['gols']):
      print(f'  No jogo {i+1} fez {g} gols.')
  print('--'*30)

print('<< VOLTE SEMPRE >>')