# -*- coding: utf-8 -*-
"""ex091.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Du5nCu9_ZxZjce7z8RzbbiKGfyOVDU-3
"""

'''
Crie um programa onde 4 jogadores joguem um dado
e tenham resultados aleatórios.
Guarde esses resultados em um dicionário em Python.
No final, coloque esse dicionário em ordem,
sabendo que o vencedor tirou o maior número no dado.
'''

from random import randint
from time import sleep
from operator import itemgetter
print('='*30)
print(f"{'Jogo de dados em Python':^30}")
print('='*30)
print('\n\n\n')

jogo = {
    'jogador1': randint(1,6),
    'jogador2': randint(1,6),
    'jogador3': randint(1,6),
    'jogador4': randint(1,6)
}

ranking = dict()
print('Valores sorteados:')
for key, value in jogo.items():
    print(f'{key} tirou {value} no dado.')
    sleep(1)
ranking = sorted(jogo.items(), key=itemgetter(1), reverse=True)
print('\n\n')
print('=== Ranking ===')
for indice, value in enumerate(ranking):
  print(f'{indice+1}º lugar: {value[0]} com {value[1]}.')
  sleep(1)