# -*- coding: utf-8 -*-
"""ex090.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmJ2Mvq_vo5BX1uB6IcujowpBz1zhOD8
"""

'''
Faça um programa que leia nome e média de um aluno,
guardando também a situação em um dicionário.
No final, mostre o conteúdo da estrutura na tela.
'''

print('='*30)
print(f"{'Dicionário em Python':^30}")
print('='*30)
print('\n\n\n')

aluno = {}


aluno['nome'] = str(input('Nome: '))
aluno['media'] = float(input('Média: '))

if aluno['media'] >= 7:
  aluno['Situação'] = 'Aprovado'
elif aluno['media'] >= 5:
  aluno['Situação'] = 'Recuperação'
else:
  aluno['Situação'] = 'Reprovado'
print(aluno)
print('='*30)
#imprimindo em laço for:
for keys, values in aluno.items():
  print(f'{keys} = {values}')