# -*- coding: utf-8 -*-
"""ex092.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwFmYbGBmypj6hCFeTXQU5Fx06l77MGO
"""

'''
Crie um programa que leia nome,
ano de nascimento e carteira de trabalho e cadastre-o
(com idade) em um dicionário.
Se por acaso a CTPS for diferente de ZERO,
o dicionário receberá também o ano de contratação e o salário.
Calcule e acrescente, além da idade,
com quantos anos a pessoa vai se aposentar.
'''

print('='*30)
print(f"{'Cadastro de trabalhador em python':^30}")
print('='*30)
print('\n\n\n')

from datetime import datetime
dados = {}
dados['nome'] = str(input('Nome: '))
nascimento = int(input('Ano de Nascimento: '))
dados['idade'] = datetime.now().year - nascimento
dados['ctps'] = int(input('Carteira de Trabalho (0 não tem): '))

if dados['ctps'] != 0:
    dados['contratação'] = int(input('Ano de Contratação: '))
    dados['salario'] = float(input('Salário: R$'))
    dados['aposentadoria'] = dados['idade'] + ((dados['contratação'] +35) - datetime.now().year)

print('--'*30)
for key, value in dados.items():
    print(f' - {key} tem o valor {value}')