# -*- coding: utf-8 -*-
"""ex016

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxJ9ZRBAWFm4-8wkuvbSmpIOTHZJtHFz
"""

from math import trunc
num = float(input("Digite um número real: "))
print("O número digitado foi {} e sua porção inteira corresponde a {}".format(num, trunc(num)))