# -*- coding: utf-8 -*-
"""ex017

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zcbc-aXyW9lQjTw8OIpaaeKjNKPnm0S
"""

import math
print("=== Catetos e Hipotenusa ===")
print("Faça um programa que leia o comprimento do cateto oposto e do cateto adjacente de um triângulo retângulo. Calcule e mostre o comprimento da hipotenusa\n\n\n")

oposto = float(input("Digite o valor do cateto oposto: "))
adjacente = float(input("Digite o valor do cateto adjacente: "))
hipotenusa = math.hypot(oposto, adjacente)
print("O valor da hipotenusa é: {:.2f}".format(hipotenusa))