# -*- coding: utf-8 -*-
"""ex018

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xIeSumfdFgoapjPYeGw8AGXB7dPH4qB
"""

import math
print("=== Seno, Cosseno e Tangente ===")
print("Faça um programa que leia um ângulo qualquer e mostre na tela o valor do seno, cosseno e tangente desse ângulo.\n\n\n")

angulo = float(input("Digite o ângulo que você deseja: "))
cosseno = math.cos(math.radians(angulo))
seno = math.sin(math.radians(angulo))
tangente = math.tan(math.radians(angulo))

print("O angulo digitado foi {}°, seu COSSENO é igual a {:.2f}, seu SENO é igual a {:.2f} e sua TANGENTE é igual a {:.2f}".format(angulo, cosseno, seno, tangente))