# -*- coding: utf-8 -*-
"""ex019

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzWOkZwXX-Y_LYAZ1Wn0qx97BJIX-G3g
"""

import random
print("=== Sorteando um item na lista ===")
print("Um professor quer sortear um dos seus quatro alunos para apagar o quadro. Faça um programa que ajude ele, lendo o nome dos alunos e escrevendo na tela o nome do escolhido.")

aluno1 = input("Primeiro aluno: ")
aluno2 = input("Segundo aluno: ")
aluno3 = input("Terceiro aluno: ")
aluno4 = input("Quarto aluno: ")
lista = [aluno1, aluno2, aluno3, aluno4]
escolhido = random.choice(lista)

print("O aluno escolhido foi {}".format(escolhido))