# -*- coding: utf-8 -*-
"""ex020

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAl0MDtYKxxmGnxfZ6sySZQr_TG55HGb
"""

import random
print("=== Ordem da lista ===")
print("O mesmo professor do desafio 19 quer sortear a ordem de apresentação de trabalhos dos alunos. Faça um programa que leia o nome dos quatro alunos e mostre a ordem sorteada.\n\n\n")

aluno1 = input("Digite o nome do primeiro aluno: ")
aluno2 = input("Digite o nome do segundo aluno: ")
aluno3 = input("Digite o nome do terceiro aluno: ")
aluno4 = input("Digite o nome do quarto aluno: ")

lista = [aluno1, aluno2, aluno3, aluno4]
random.shuffle(lista)

print("A ordem de apresentação dos trabalhos será: ")
print(lista)