# -*- coding: utf-8 -*-
"""ex023

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7B8v_nK5SgIfIqyxHJrEIriTKFQjnEN
"""

print("=-=-= Separando dígitos =-=-=")
print("Faça um programa que leia um número de 0 a 9999 e mostre na tela cada um dos dígitos separados.")

numero = int(input("Digite um número de 0 a 9999: "))
unidade = numero // 1 % 10 #obtem a unidade (// pois retorna somente números inteiros)
dezena = numero // 10 % 10 #obtem a dezena
centena = numero // 100 % 10 #obtem a centena
milhar = numero // 1000 % 10 #obtem a milhar
print("A unidade é o número {}".format(unidade))
print("A dezena é o número {}".format(dezena))
print("A centena é o número {}".format(centena))
print("A milhar é o número {}".format(milhar))