# -*- coding: utf-8 -*-
"""ex022

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17scsSVldKNWTxXH25Jxb9TvliLdMSrRK
"""

print("=-=-= Analisador de textos =-=-=")
print("Crie um programa que leia o nome completo de uma pessoa e mostre o nome com todas as letras maiúsculas e minúsculas.\n\n\n")

nome = input("Digite seu nome completo: ").strip()#remove os espaços


print("Seu nome em maiúsculas: {}".format(nome.upper()))#deixa em maiúsculo
print("Seu nome em minúsculas: {}".format(nome.lower()))#deixa em minúsculos
print("Seu nome tem {} ".format(len(nome) - nome.count(' ')))#conta os caracteres e elimina os espaços, pois esta subtraindo com o nome.count(' ')
print("Seu primeiro nome tem {}".format(nome.find(' ')))#conta até achar o primeiro espaço
separador = nome.split()#fatia cada nome em forma de lista
print("Seu primeiro nome é {} e ele tem {} letras".format(separador[0], len(separador[0])))#encontra na lista a posição 0, com isso será o primeiro nome digitado, e o len conta a quantidade de caracteres.