# -*- coding: utf-8 -*-
"""ex021

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cbct_yVSh_IKQaEXJ55Cd6146ZuYH9pa
"""

import pygame
pygame.init()
print("=== tocando um mp3 ===")
print("Faça um programa em Python que abra e reproduza o áudio de um arquivo MP3.\n\n\n")

#somente de exemplo, o arquivo .MP3 tem que estar na mesma pasta.
pygame.mixer.music.load(ExemploDeArquivo.mp3) #carrega o arquivo
pygame.mixer.music.play()#toca a música
pygame.event.wait()#espera o evento terminar para encerrar o programa