# -*- coding: utf-8 -*-
"""ex026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2NGpw3_3gfK-b7uuHct5L5CsBV3mPH-
"""

print("=-=-= Primeira e ultima ocorrencia de uma string =-=-=")
print("""Faça um programa que leia uma frase pelo teclado e mostre quantas vezes aparece a letra “A”,
em que posição ela aparece a primeira vez e em que posição ela aparece a última vez.\n\n\n""")

frase = str(input("Digite uma frase: ")).upper().strip()#deixa em maiúsculo e elimina os espaços
print(f"A letra A aparece {frase.count('A')} vezes na frase.")#Soma a quantidade de A aparece
print(f"A primeira letra A apareceu na posição {frase.find('A')+1}")#procura a primeira letra a +1, devido ao índice começar com zero
print(f"A ultima letra A apareceu na posição {frase.rfind('A')+1}")#procura a partir do lado direito a lera a.