# -*- coding: utf-8 -*-
"""ex025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQs8gPwZZlLTJLenVBqmWeI5g_R0Fg2o
"""

print("=-=-= Procurando uma string dentro da outra =-=-=")
print("Crie um programa que leia o nome de uma pessoa e diga se ela tem “SILVA” no nome.\n\n\n")

nome = str(input("Digite seu nome completo: ")).strip().upper()#Elimina os espaços e deixa tudo em maiúsculo
print("Seu nome tem Silva? {}".format("SILVA" in nome.upper()))#Retorna true se tiver SILVA