# -*- coding: utf-8 -*-
"""ex024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SND949ipPTjQIzV15yGDDI68ZSALYOx8
"""

print("=-=-= Verificando as primeiras letras =-=-=")
print("Crie um programa que leia o nome de uma cidade diga se ela começa ou não com o nome “SANTO”.\n\n\n")

cidade = str(input("Em que cidade você nasceu? ")).strip()#Elimina os espaços
print(cidade[:5].upper() == 'SANTO')#deixa tudo em maiúsculo para comparar