# -*- coding: utf-8 -*-
"""ex027

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVOy0nfaBMIXOAQo_NzsIb-j_mFT9-w4
"""

print("Primeiro e Último nome de uma pessoa")
print("""Faça um programa que leia o nome completo de uma pessoa,
mostrando em seguida o primeiro e o último nome separadamente.\n\n\n""")

nome = str(input("Digite seu nome completo: ")).strip()
n = nome.split()#fatia o nome em uma lista
print(f'Seu primeiro nome é {n[0]}')#pega o primeiro elemento da lista
print(f'Seu último nome é {n[len(n)-1]}')#pega o ultimo elemento da lista