# -*- coding: utf-8 -*-
"""ex099.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cj970xGRqRbO8GPR96tNSLZ5jd78Fy4w
"""

'''
Faça um programa que tenha uma função chamada maior(),
que receba vários parâmetros com valores inteiros.
Seu programa tem que analisar todos os valores
e dizer qual deles é o maior.
'''

print('='*30)
print(f"{'Função que descobre o maior':^30}")
print('='*30)
print('\n\n\n')

def maior(*num):
  print(f'Recebido os números: {num}')
  print(f'O maior número é: {max(num)}')
  print('-'*30)

#programa principal
maior(2, 5, 3, 9, 10, 7)
maior(4, 7, 0)
maior(1, 2)