# -*- coding: utf-8 -*-
"""ex096.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xISdSji090HfF1OVKcISLq6WxYvvqs2-
"""

'''
Faça um programa que tenha uma função chamada área(),
que receba as dimensões de um terreno retangular (largura e comprimento)
e mostre a área do terreno.
'''

print('='*30)
print(f"{'Função que calcula área':^30}")
print('='*30)
print('\n\n\n')

def area(a, b):
  print('-'*30)
  area = a * b
  print(f'A área de {a} x {b} é igual a {area:.2f}m².')
  print('-'*30)

a = float(input('Digite a largura do terreno: '))
b = float(input('Digite o comprimento do terreno: '))
area (a, b)