# -*- coding: utf-8 -*-
"""ex098.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHpf3BYzRICcwQ9QWZRiJo8sq_dJJ5yh
"""

'''
Faça um programa que tenha uma função chamada contador(),
que receba três parâmetros: início, fim e passo.
Seu programa tem que realizar três contagens através da função criada:
a) de 1 até 10, de 1 em 1
b) de 10 até 0, de 2 em 2
c) uma contagem personalizada
'''
print('='*30)
print(f"{'Função de contador.':^30}")
print('='*30)
print('\n\n\n')

from time import sleep

def contador (inicio, fim, passo):
  print('=-'*30)
  print(f'Contagem de {inicio} até {fim} de {passo} em {passo}:')

  if passo < 0:
    passo *= -1
  if passo == 0:
    passo = 1

  if inicio < fim:
    cont = inicio
    while cont <= fim:
      print(f'{cont} ', end='')
      sleep(0.5)
      cont += passo
    print('Fim')
  else:
    cont = inicio
    while cont >= fim:
      print(f'{cont} ', end='')
      sleep(0.5)
      cont -= passo
    print('Fim')


#programa principal
contador(1, 10, 1)
contador(10, 0, 2)
print('=-'*30)
print('Agora é a sua vez de personalizar a contagem!')
ini = int(input('Início:  '))
fi = int(input('Fim:        '))
pas = int(input('Passo:    '))
contador(ini, fi, pas)