# -*- coding: utf-8 -*-
"""ex097.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3UyJvgstcWPEi4RA_1fKlNDb1vm9MDm
"""

'''
Faça um programa que tenha uma função chamada escreva(),
que receba um texto qualquer como parâmetro e mostre uma mensagem com tamanho adaptável.
'''

print('='*30)
print(f"{'Um print especial':^30}")
print('='*30)
print('\n\n\n')

def escreva(txt):
  print('~'* len(txt))
  print(txt)
  print('~'* len(txt))

#programa principal
escreva('Olá, Mundo!')
escreva('Python')
escreva('Curso em Vídeo')