# -*- coding: utf-8 -*-
"""ex103.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYFFfb3KRNa78XhPnMihkH83H6l0Js3A
"""

'''
Faça um programa que tenha uma função chamada ficha(),
que receba dois parâmetros opcionais: o nome de um jogador e quantos gols ele marcou.
O programa deverá ser capaz de mostrar a ficha do jogador, mesmo que algum dado não tenha sido informado corretamente.
'''
print('='*30)
print(f"{'Ficha do Jogador':^30}")
print('='*30)
print('\n\n\n')

def ficha(nome='*Desconhecido*', gol=0):
    print(f'O jogador {nome} fez {gols} gol(s) no campeonato.')


#Programa principal
nome1 = str(input('Nome do jogador: '))
gols = str(input('Quantidade de gols: '))
if gols.isnumeric():
    gols = int(gols)
else:
    gols = 0
if nome1.strip() == '':
    ficha(gol = gols)
else:
    ficha(nome1, gols)