# -*- coding: utf-8 -*-
"""ex106.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXIZ718YlHqR3zeB8Y8vABikIQyolHNH
"""

'''
Faça um mini-sistema que utilize o Interactive Help do Python.
O usuário vai digitar o comando e o manual vai aparecer.
Quando o usuário digitar a palavra ‘FIM’, o programa se encerrará.
Importante: use cores.
'''

print('-'*30)
print(f'{"Interactive helping system in python"*30}')
print('-'*30)

c = ('\033[m', #0 - sem cores
     '\033[0;30;41m', #1 - vermelho
     '\033[0;30;42m', #2 - verde
     '\033[0;30;43m', #3 - amarelo
     '\033[0;30;44m', #4 - azul
     '\033[0;30;45m', #5 - roxo
     '\033[7;30m' #6 - branco

    );

def ajuda(com):
  titulo(f'Acessando o manual do comando \'{com}\'', 4)
  print(c[6], end='')
  help(com)
  print(c[0], end='')

def titulo(msg, cor = 0):
  print(c[cor], end='')
  tam = len(msg) +4
  print('='*tam)
  print(f' {msg}')
  print('='*tam)
  print(c[0], end='')


#programa principal
comando = ''
while True:
  titulo('SISTEMA DE AJUDA PyHELP', 2)
  comando = str(input('Função ou Biblioteca >'))
  if comando.upper() == 'FIM':
    break
  else:
    ajuda(comando)
titulo('Até logo', 1)