# -*- coding: utf-8 -*-
"""ex102.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Luh6NeQOVxyZMyNC2FIAMXYaZ8nlR1YM
"""

'''
Crie um programa que tenha uma função fatorial() que receba dois parâmetros:
o primeiro que indique o número a calcular e outro chamado show,
ue será um valor lógico (opcional) indicando se será mostrado ou não na tela
o processo de cálculo do fatorial.
'''
print('='*30)
print(f"{'Função para fatorial':^30}")
print('='*30)
print('\n\n\n')

def fatorial(numero, show=False):
    """
    -> Calcula o fatorial de um número.
    :param num: O número a ser calculado.
    :param show: (opcional) Mostrar ou não a conta.
    :return: O valor do fatorial de um número num.
    """
    f = 1
    for c in range(numero, 0, -1):
      if show:
        print(c, end='')
        if c > 1:
          print(' x ', end='')
        else:
          print(' = ', end='')
      f *= c
    return f

#programa principal
print(fatorial(8, show=True))