# -*- coding: utf-8 -*-
"""ex100.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsxhaZnjNU1gq8QOEbEGCAXNN8tPQLOa
"""

'''
Faça um programa que tenha uma lista chamada números e duas funções chamadas
sorteia() e somaPar().
A primeira função vai sortear 5 números e vai colocá-los dentro da lista
e a segunda função vai mostrar a soma entre todos os valores pares
sorteados pela função anterior.
'''

print('='*30)
print(f"{'Funções de sortear e somar.':^30}")
print('='*30)
print('\n\n\n')


from random import randint
numeros = []
def sorteia():
  for c in range(0, 5):
    num = randint(1, 20)
    numeros.append(num)
  print("Dada a lista: ", end='')
  for c in range(0, len(numeros)):
    print(f'{numeros[c]} | ', end=' ')
  print()


def somaPar():

  soma = 0
  for c in range (1, len(numeros)):
    if numeros[c] % 2 == 0:
      soma += numeros[c]
  print(f'a soma dos pares é: {soma}')

#programa principal
sorteia()
somaPar()