# -*- coding: utf-8 -*-
"""ex105.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UiAxhe-c1sCzi2EW6KMBx5zf9xMgrlGa
"""

'''
Faça um programa que tenha uma função notas() que pode receber várias notas de
alunos e vai retornar um dicionário com as seguintes informações:

– Quantidade de notas;
– A maior nota;
– A menor nota;
- A médoa da turma;
- A situação (opcional)
'''

print('-'*30)
print(f'{"Função de notas escolares"*30}')
print('-'*30)

def notas(*n, sit=False):
  """
  -> Função para analisar notas e situações de vários alunos.
  :param n: uma ou mais notas dos alunos (aceita várias)
  :param sit: valor opcional, indicando se deve ou não adicionar a situação
  :return: dicionário com várias informações sobre a situação
  """
  r = dict()
  r['total'] = len(n)
  r['maior'] = max(n)
  r['menor'] = min(n)
  r['media'] = sum(n)/len(n)
  if sit:
    if r['media'] >= 7:
      r['situacao'] = 'Aprovado'
    elif r['media'] >= 5:
      r['situacao'] = 'Recuperação'
    else:
      r['situacao'] = 'Reprovado'

  return r

#Programa Principal
resp = notas(8.5, 9.5, 5, 6.5, sit=True)
print(resp)