# -*- coding: utf-8 -*-
"""ex104.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YgAVHO22ZbYLvTeFQYzalAzq5EQkDFS
"""

'''
Crie um programa que tenha a função leiaInt(),
que vai funcionar de forma semelhante ‘
a função input() do Python, só que fazendo a validação
para aceitar apenas um valor numérico.
Ex: n = leiaInt(‘Digite um n: ‘)
'''

print('='*30)
print(f"{'Validando entrada de dados em Python':^30}")
print('='*30)
print('\n\n\n')

def leiaInt(msg):
  ok = False
  valor = 0
  while True:
    n = str(input(msg))
    if n.isnumeric():
      valor = int(n)
      ok = True
    else:
      print('\033[0;31mERRO! Digite um número inteiro válido.\033[m')
    if ok:
      break
  return valor

#programa principal
n = leiaInt('Digite um número: ')
print(f'Você acabou de digitar o número {n}')