# -*- coding: utf-8 -*-
"""ex101.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Km5G4l86L9eAmZCpdVpTffy7vNP7omm
"""

'''
Crie um programa que tenha uma função chamada voto()
que vai receber como parâmetro o ano de nascimento de uma pessoa,
retornando um valor literal indicando se uma pessoa tem voto
NEGADO, OPCIONAL e OBRIGATÓRIO nas eleições.
'''
print('='*30)
print(f"{'Funções para votação':^30}")
print('='*30)
print('\n\n\n')

from datetime import date
def voto(ano):
    atual = date.today().year
    idade = atual - ano
    if idade < 16:
        return f'Com {idade} anos: NÃO VOTA.'
    elif idade >= 16 and idade < 70:
        return f'Com {idade} anos: VOTO OBRIGATÓRIO.'
    else:
        return f'Com {idade} anos: VOTO OPCIONAL.'

#programa principal.
nasc = int(input('Em que ano você nasceu? '))
print(voto(nasc))