# -*- coding: utf-8 -*-
"""ex045

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WD1FdOE-b0oa1ur81-CKxqbPK6Td56n1
"""

#Crie um programa que faça o computador jogar Jokenpô com você.

print("="*30)
print('=== Jan Ken Po ==')
print("="*30)
print("\n\n\n")

from time import sleep
from random import choice

jogador = int(input('''Digite uma opção:
[1]Pedra
[2]Papel
[3]Tesoura: '''))

escolha = [1, 2, 3]
computador = choice(escolha)
print('')
sleep(1)
print('JAN')
sleep(1)
print('KEN')
sleep(1)
print('PO')
sleep(1)

#Jogador escolhendo pedra:
if jogador == 1 and computador == 1:
  print('Jogador escolheu PEDRA e o computador escolheu PEDRA')
  print('Empate!')
elif jogador == 1 and computador == 2:
  print('Jogador escolheu PEDRA e o computador escolheu PAPEL')
  print('Você perdeu!')
elif jogador == 1 and computador == 3:
  print('Jogador escolheu PEDRA e o computador escolheu TESOURA')
  print('Você ganhou!')

#Jogador escolhendo papel:
if jogador == 2 and computador == 1:
  print('Jogador escolheu PAPEL e o computador escolheu PEDRA')
  print('Voce ganhou!')
elif jogador == 2 and computador == 2:
  print('Jogador escolheu PAPEL e o computador escolheu PAPEL')
  print('Empate')
elif jogador == 2 and computador == 3:
  print('Jogador escolheu PAPEL e o computador escolheu TESOURA')
  print('Voce perdeu!')

#Jogador escolhendo tesoura:
if jogador == 3 and computador == 1:
  print('Jogador escolheu TESOURA e o computador escolheu PEDRA')
  print('Voce perdeu!')
if jogador == 3 and computador == 2:
  print('Jogador escolheu TESOURA e o computador escolheu PAPEL')
  print('Voce ganhou!')
if jogador == 3 and computador == 3:
  print('Jogador escolheu TESOURA e o computador escolheu TESOURA')
  print('Empate!')