# -*- coding: utf-8 -*-
"""ex049

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6RkGCQwqNAhpgSBFO75R4g7ct2H-3cO
"""

#mostrando a tabuada de um número que o usuário escolher, só que agora utilizando um laço for.

print("="*30)
print("Tabuada 2.0")
print("="*30)
print("\n\n\n")

numero = int(input("Digite um número: "))
for c in range(1, 11):
  print(f'{numero} X {c} = {numero * c}')
print("="*30)