# -*- coding: utf-8 -*-
"""ex048

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBwnfF8-mvohYdapksc2rWguUywxGaQx
"""

#Faça um programa que calcule a soma entre todos os números que são múltiplos de três e que se encontram no intervalo de 1 até 500.

print("="*30)
print("Soma ímpares")
print("="*30)
print("\n\n\n")

contador = 0
for c in range (1, 501, 2):
  if c % 3 == 0:
    contador = contador + c
print(f'O resultado da soma dos múltiplos de 3 no intervalo de 1 a 500 é de {contador}!')