# -*- coding: utf-8 -*-
"""ex046

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-a7MxCy4Jpd0q-wHnel-gAPDsxuOfeu4
"""

#Faça um programa que mostre na tela uma contagem regressiva para o estouro de fogos de artifício, indo de 10 até 0, com uma pausa de 1 segundo entre eles.
print('='*50)
print('Contagem Regressiva para o estouro de fogos de artifício')
print('='*50)
from time import sleep

for c in range (10, -1, -1):
    print(c)
    sleep(1)
print('='*50)
print('BUM! BUM! POOOW!')
print('='*50)