# -*- coding: utf-8 -*-
"""ex047

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pvv5Z5GdJ_Xepx9wrYSYcDSc7nFjtlE4
"""

#Crie um programa que mostre na tela todos os números pares que estão no intervalo entre 1 e 50.
print("="*30)
print("Números pares entre 1 e 50")
print("="*30)
print('\n\n\n')
for c in range (1, 51):
  if c % 2 == 0:
    print(c, end=' ')