# -*- coding: utf-8 -*-
"""ex056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uY9UfkrQIKRVRQFjoEl5ojnjPTu_XYW
"""

# Desenvolva um programa que leia o nome, idade e sexo de 4 pessoas.
#No final do programa, mostre: a média de idade do grupo,
#qual é o nome do homem mais velho e quantas mulheres têm menos de 20 anos.

print("="*30)
print("Analisador completo")
print("="*30)
print("\n\n\n")

total = 0
nome_velho = ''
idade_velho = 0
total_mulher = 0



for c in range (1, 5):
  nome = (input(f'Digite o nome da {c} pessoa: ')).upper()
  sexo = (input(f'Digite o sexo da {c} pessoa [M/F]: ')).upper()
  idade = int(input(f'Digite a idade da {c} pessoa: '))
  print('_'*25)
  total += idade
  if c == 1 and sexo == 'M':
    nome_velho = nome
    idade_velho = idade
  if sexo == 'M' and idade > idade_velho:
    nome_velho = nome
    idade_velho = idade
  if sexo == 'F' and idade < 20:
    total_mulher += 1

print(f'A média de idade do grupo é de {total / 4:.1f} anos')
print(f'O nome do homem mais velho é {nome_velho} com {idade_velho}. ')
print(f'O total de mulheres menores de 20 anos é de: {total_mulher}')