# -*- coding: utf-8 -*-
"""ex055.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yEMnYav8r68VTb89l-NIryFUW-k1lR2
"""

#Faça um programa que leia o peso de cinco pessoas.
#No final, mostre qual foi o maior e o menor peso lidos.

print("="*30)
print("Maior e menor peso")
print("="*30)
print("\n\n\n")

maior = 0
menor = 0
for c in range (1, 6):
  peso = float(input(f"Digite o peso da {c}ª pessoa: "))
  if c == 1:
    maior = peso
    menor = peso
  else:
    if peso > maior:
      maior = peso
    if peso < menor:
      menor = peso

print(f'O maior peso digitado foi: {maior}')
print(f'O menor peso digitado foi: {menor}')