# -*- coding: utf-8 -*-
"""ex050

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ade6dabz_IOEZTRMbwJHaJeu_3Or5hu5
"""

#Desenvolva um programa que leia seis números inteiros e mostre a soma apenas daqueles que forem pares. Se o valor digitado for ímpar, desconsidere-o.

print("="*30)
print('Soma dos pares')
print('='*30)
print('\n\n\n')
soma = 0
for c in range (0, 6):
  numero = int(input(f'Digite o {c+1}º número: '))
  if numero % 2 == 0:
    soma = soma + numero
print(f'A soma dos números pares é {soma}')