# -*- coding: utf-8 -*-
"""ex053.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVHL7Ax-Mfs-hAHee5qrVJe-nzUJNPfx
"""

#Crie um programa que leia uma frase qualquer e diga se ela é um palíndromo, desconsiderando os espaços.

print("="*30)
print("VERIFICADOR DE PALÍNDROMO")
print("="*30)
print("\n\n\n")

frase = str(input("Digite uma frase: ")).strip().upper()
palavras = frase.split()
junto = ''.join(palavras)
inverso = ''
for letra in range(len(junto) -1, -1, -1):
    inverso += junto[letra]
print(f'A frase {frase} de trás para frente é {inverso}')
if inverso == junto:
  print("Temos um palíndromo!")
else:
  print("Não é um palíndromo")