# -*- coding: utf-8 -*-
"""ex051

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNGdYH883cLdAkjxDdz17X1kPk2a0VJI
"""

#Desenvolva um programa que leia o primeiro termo e a razão de uma PA. No final, mostre os 10 primeiros termos dessa progressão.

print("="*30)
print('Progressão aritimética')
print('='*30)
print('\n\n\n')

termo = int(input('Digite o primeiro termo da PA: '))
razao = int(input('Digite a razão da PA: '))

for c in range(1, 11):
    print(termo, end=' -> ')
    termo += razao