# -*- coding: utf-8 -*-
"""ex052.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135u71-rV0cl3AtW6_Nl_n48Agos58JrO
"""

#Faça um programa que leia um número inteiro e diga se ele é ou não um número primo.
print("="*30)
print("Número primo")
print('='*30)
print("\n\n\n")

numero = int(input("Digite um número: "))
contador = 0
for c in range (1, numero+1):
  if numero % c == 0:
    contador += 1
  print(f'{c}', end=' ')
print(f'\nO número {numero} foi divisível {contador} vezes')
if contador == 2:
  print('Temos um número primo')
else:
  print('Não temos um número primo')