# -*- coding: utf-8 -*-
"""ex054.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Prx4L378LhkiRSJZN7SjXFRvjDeNMUL
"""

#Crie um programa que leia o ano de nascimento de sete pessoas.
#No final, mostre quantas pessoas ainda não atingiram a maioridade e quantas já são maiores.

print('='*30)
print('Grupo da maioridade')
print('='*30)
print('\n\n\n')
from datetime import date
atual = date.today().year
maior = 0
menor = 0
for c in range (1, 8):
  idade = int(input(f'Em que ano a {c}ª pessoa nasceu? '))
  if atual - idade >= 18:
    maior += 1
  else:
    menor += 1
print(f'Temos um total de {maior} pessoas maiores de idade.')
print(f'Temos um total de {menor} pessoas menores de idade.')