# -*- coding: utf-8 -*-
"""ex073.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDwWHkGznuGUjscb5LchFANNM1nfGlOA
"""

''' Crie uma tupla preenchida com os 20 primeiros colocados da Tabela do Campeonato Brasileiro
de Futebol, na ordem de colocação. Depois mostre:

a) Os 5 primeiros times.

b) Os últimos 4 colocados.

c) Times em ordem alfabética.

d) Em que posição está o time do Bragantino.
'''

print("="*30)
print(f"{'Tuplas com times de Futebol':^30}")
print('='*30)
print('\n\n\n')

brasileirao = ('Flamengo', 'Palmeiras', 'Cruzeiro', 'Mirassol', 'Fluminense',
               'Botafogo', 'Bahia', 'São Paulo', 'Grêmio','Bragantino',
               'Atlético Mineiro', 'Santos', 'Corinthians', 'Vasco', 'Vitória',
               'Internacional', 'Ceará', 'Fortaleza', 'Juventude', 'Sport Recife')
cinco_primeiros = brasileirao[0:5]
quatro_ultimos = brasileirao[-4:]
bragantino = brasileirao.index('Bragantino') + 1

print(f'No ano de 2025, os 5 primeiros colocados do Brasileirão foram: {cinco_primeiros}.')
print('=-'*30)
print(f'E os 4 últimos foram: {quatro_ultimos}.')
print('=-'*30)
print(f'E o Bragantino terminou a competição em {bragantino}º lugar.')
print('=-'*30)