# -*- coding: utf-8 -*-
"""ex074.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwt5HjNt5z3TKuiMBl4ZiN7LlnNV7Mcg
"""

'''Crie um programa que vai gerar cinco números aleatórios e colocar em uma tupla.
 Depois disso, mostre a listagem de números gerados
 e também indique o menor e o maior valor que estão na tupla.'''

print('='*30)
print(f"{'Gerador de números aleatórios':^30}")
print('='*30)
print('\n\n\n')

from random import randint
tupla = (randint(1, 10), randint(1, 10), randint(1, 10), randint(1, 10), randint(1, 10))
maior = menor = tupla[0]

#forma lógica de resolução.
for n in tupla:
  if n > maior:
    maior = n
  if n < menor:
    menor = n

#forma do python de resolução
'''
print(f'Os valores sorteados foram: {tupla}')
print('=-'*15)
print(f'O maior valor sorteado foi: {max(tupla)}')
print('=-'*15)
print(f'O menor valor sorteado foi: {min(tupla)}')
'''

print(f'Os valores sorteados foram: {tupla}')
print('=-'*15)
print(f'O maior valor sorteado foi: {maior}')
print('=-'*15)
print(f'O menor valor sorteado foi: {menor}')
print('=-'*15)