# -*- coding: utf-8 -*-
"""ex075.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYcRnPWMZduqkmgjw1I9R8BbA5cd09AN
"""

'''
Desenvolva um programa que leia quatro valores pelo teclado e guarde-os em uma tupla.
No final, mostre:

A) Quantas vezes apareceu o valor 9.

B) Em que posição foi digitado o primeiro valor 3.

C) Quais foram os números pares.
'''

print("="*30)
print(f"{'Análise de dados em uma Tupla':^30}")
print("="*30)
print('\n\n\n')

tupla = (int(input("Digite um número: ")),
         int(input("Digite outro número: ")),
         int(input("Digite mais um número: ")),
         int(input("Digite o último número: ")))

print(f"\nVocê digitou os valores {tupla}")

print(f"\nO valor 9 apareceu {tupla.count(9)} vezes")

if 3 in tupla:
  print(f"O valor 3 apareceu na {tupla.index(3) + 1}ª posição")
else:
  print("O valor 3 não foi digitado em nenhuma posição")

print('Os números pares digitados foram: ', end=' ')
for c in range(0, len(tupla)):
    if  c % 2 == 0:
        print(c, end=' ')