# -*- coding: utf-8 -*-
"""ex077.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7o-tzuGxsJ37g5ZjjMdMnXZ_BWIHDd5
"""

'''
Crie um programa que tenha uma tupla com várias palavras (não usar acentos).
Depois disso, você deve mostrar, para cada palavra, quais são as suas vogais.
'''

print('='*30)
print(f"{'Vogais nas palavras':^30}")
print('='*30)
print('\n\n\n')

palavras = ('aprender', 'programar', 'linguagem', 'python',
            'curso', 'gratis', 'estudar', 'praticar', 'trabalhar',
            'mercado', 'programador', 'futuro')

for p in palavras:
    print(f'\nNa palavra {p.upper()} temos ', end='')
    for letra in p:
        if letra.upper() in 'AEIOU':
            print(letra.upper(), end=' ')