# -*- coding: utf-8 -*-
"""ex076.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Syc2N5nVf5zp3XUSvLDIwe71Vd9X28xX
"""

'''Crie um programa que tenha uma tupla única com nomes de produtos
e seus respectivos preços, na sequência.
No final, mostre uma listagem de preços, organizando os dados em forma tabular.'''

print('='*30)
print(f"{'Lista de preços com tupla':^30}")
print('='*30)
print('\n\n\n')

print('=-'*15)
print(f"{'Materiais escolares:':^30}")
print('=-'*15)

listagem = ('Lápis', 1.75,
         'Borracha', 2,
         'Caderno', 15.90,
         'Estojo', 25,
         'Transferidor', 4.20,
         'Compasso', 9.99,
         'Mochila', 120.90,
         'Canetas', 22.30,
         'Livro', 34.90)

for item in range (0, len(listagem)):
  if item % 2 == 0:
    print(f'{listagem[item]:.<30}', end='')
  else:
    print(f'R${listagem[item]:>7.2f}')
print('=-'*15)