# -*- coding: utf-8 -*-
"""ex072.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179EIZbLsnrggcQWozpT3RC_kOjk-Lsi5
"""

'''Crie um programa que tenha uma dupla totalmente preenchida com uma contagem por extenso,
de zero até vinte.
Seu programa deverá ler um número pelo teclado (entre 0 e 20) e mostrá-lo por extenso.'''

print('='*30)
print(f"{'Extenso':^30}")
print('='*30)
print('\n\n\n')

extenso = ('zero', 'um', 'dois', 'três', 'quatro', 'cinco',
           'seis', 'sete', 'oito', 'nove', 'dez',
           'onze', 'doze', 'treze', 'catorze', 'quinze',
           'dezesseis', 'dezessete', 'dezoito', 'dezenove', 'vinte')


while True:
    numero = int(input('Digite um número entre 0 e 20: '))
    if numero >=0 and numero <= 20:
        break
    print('Tente novamente.', end=' ')
print(f'O número digitado foi {extenso[numero]}')