# -*- coding: utf-8 -*-
"""ex079.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghUVoPZkOTl29nGOKZ7mq78XF8cOzbde
"""

'''
Crie um programa onde o usuário possa digitar vários valores numéricos
 e cadastre-os em uma lista. Caso o número já exista lá dentro,
 ele não será adicionado.
 No final, serão exibidos todos os valores únicos digitados, em ordem crescente.
'''

print('='*30)
print(f"{'Valores únicos em ordem crescente':^30}")
print('='*30)
print('\n\n\n')

lista = []
while True:
  num = int(input('Digite um valor: '))
  if num not in lista:
    lista.append(num)
    print('Número adicionado a lista!')
  else:
    print('Valor duplicado não será adicionado!')
  continua = str(input('Quer continuar? [S/N]: ')).strip().upper()[0]
  print('=-'*15)
  if continua not in 'SN':
    print('Opção inválida!')
    continua = str(input('Quer continuar? [S/N]: ')).strip().upper()[0]
  if continua == 'N':
    break
lista.sort()
print(f'Os números adicionados foram: {lista}')