# -*- coding: utf-8 -*-
"""ex078.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFN1E45cZCFayYBwAJacgxYvlreaNhD2
"""

'''
Faça um programa que leia 5 valores numéricos e guarde-os em uma lista.
No final, mostre qual foi o maior e o menor valor digitado e as suas respectivas
posições na lista.
'''

print('='*30)
print(f"{'Valores na lista':^30}")
print('='*30)

maior = menor = 0

lista = []
for c in range(0, 5):
  lista.append(int(input(f'Digite um valor para a posição {c}: ')))
  #verifica o maior e o menor número.
  if c == 0:
    maior = menor = lista[c]
    posicao_maior = posicao_menor = c
  else:
    if lista[c] > maior:
      maior = lista[c]
      posicao_maior = c
    if lista[c] < menor:
      menor = lista[c]
      posicao_menor = c

print('=-'*15)
print(f'Você digitou os valores {lista}')
print('=-'*15)
print(f'O maior valor digitado foi {maior} nas posições ', end='')
#varre a lista e verifica as posições do maior valor.
for indice, valor in enumerate(lista):
  if valor == maior:
    print(f'{indice}...', end='')
print()
print('=-'*15)
print(f'O menor valor digitado foi {menor} nas posições ', end='')
#varre a lista e verifica as posições do menor valor.
for indice, valor in enumerate(lista):
  if valor == menor:
    print(f'{indice}...', end='')