# -*- coding: utf-8 -*-
"""ex081.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdukWH7MyMn-8WU3jcQUoWznx0N2RvYv
"""

'''
Exercício Python 081: Crie um programa que vai ler vários números e colocar
em uma lista.Depois disso, mostre:
A) Quantos números foram digitados.
B) A lista de valores, ordenada de forma decrescente.
C) Se o valor 5 foi digitado e está ou não na lista.
'''

print('='*30)
print(f"{'Extraindo dados de uma lista':^30}")
print('='*30)
print("\n\n\n")

lista = []
while True:
  numero = int(input('Digite um número: '))
  lista.append(numero)
  continua = str(input('Quer continuar? [S/N]: ')).strip().upper()[0]
  print("=-"*15)
  if continua not in 'SN':
    print('Opção inválida. Tente novamente.')
    continua = str(input('Quer continuar? [S/N]: ')).strip().upper()[0]
  if continua == 'N':
    break
#resolução da A:
print(f'Foram digitados {len(lista)} números.')
print('=-'*15)

#resolução da B:
lista.sort(reverse=True)
print(f'Os valores em ordem decrescente são {lista}')
print('=-'*15)

#resolução da C:
if 5 in lista:
  print('O valor 5 faz parte da lista!')
else:
  print('O valor 5 não faz parte da lista!')