# -*- coding: utf-8 -*-
"""ex084.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKApF0WZqDrnYMklG5esR_-QFs5fsgja
"""

'''
Faça um programa que leia nome e peso de várias pessoas,
guardando tudo em uma lista. No final, mostre:
A) Quantas pessoas foram cadastradas.
B) Uma listagem com as pessoas mais pesadas.
C) Uma listagem com as pessoas mais leves.
'''

print("="*30)
print(f"{'Lista composta e análise de dados':^30}")
print('='*30)
print('\n\n\n')

maior = menor = 0
galera = []
dado = []

#laço que preenche a lista dado e faz o append para galera.
while True:
    nome = str(input('Nome: '))
    peso = float(input('Peso: '))
    dado.append(nome)
    dado.append(peso)
    #Já preenche a variável de peso maior e menor.
    if len(galera) == 0:
        maior = menor = dado[1]
    else:
        if dado[1] > maior:
            maior = dado[1]
        if dado[1] < menor:
            menor = dado[1]
    galera.append(dado[:])
    dado.clear()

    continua = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
    print('-'*40)
    #repete caso digite uma opção inválida.
    if continua not in 'SN':
        print('Opção inválida. Tente novamente.')
        continua = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
    if continua == 'N':
        break


#quantidade de pessoas cadastradas.
print(f'Ao todo, você cadastrou {len(galera)} pessoas.')

#nome das pessoas com o maior peso (caso duplicado).
print(f'O maior peso foi de {maior}Kg. Peso de ', end='')
for p in galera:
    if p[1] == maior:
        print(f'[{p[0]}]', end='')
print()

#nome das pessoas com menor peso (caso duplicado).
print(f'O menor peso foi de {menor}Kg. Peso de ', end='')
for p in galera:
    if p[1] == menor:
        print(f'[{p[0]}]', end='')
print()