# -*- coding: utf-8 -*-
"""ex080.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FM-jHl9tXmDIl3IYO4ytWvKkBcJKUCTO
"""

'''
Crie um programa onde o usuário possa digitar cinco valores numéricos
e cadastre-os em uma lista,
já na posição correta de inserção (sem usar o sort()).
No final, mostre a lista ordenada na tela.
'''

print('='*30)
print(f"{'Lista ordenada sem repetições'}")
print('='*30)
print('\n\n\n')

lista = []
for c in range (0, 5):
  numero = int(input('Digite um número: '))
  if c == 0 or numero > lista[-1]:
    lista.append(numero)
    print('Adicionado ao final da lista...')
  else:
    posicao = 0
    while posicao < len(lista):
      if numero <= lista[posicao]:
        lista.insert(posicao, numero)
        print(f'Adicionado na posição {posicao} da lista...')
        break
      posicao += 1

print('=-'*25)
print(f'OS valoires da Lista: {lista}')