# -*- coding: utf-8 -*-
"""ex087.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STKBDtWSHq35gzwr86rvTAeQtW1C7tOd
"""

'''
Aprimore o desafio anterior, mostrando no final:
A) A soma de todos os valores pares digitados.
B) A soma dos valores da terceira coluna.
C) O maior valor da segunda linha.
'''

print("="*30)
print(f"{'Matrizes em python 2.0':^20}")
print("="*30)
print("\n\n\n")

matriz = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
par = soma = maior = 0
#Alimentando a matriz.
for linha in range (0,3):
    for coluna in range (0,3):
        matriz[linha][coluna] = int(input(f"Digite um valor para [{linha}, {coluna}]: "))
print("=-"*30)
#Alinhando a matriz.
for linha in range (0,3):
    for coluna in range (0,3):
        print(f"[{matriz[linha][coluna]:^5}]", end="")
    print()
print("=-"*30)
#Resolução da A:
for linha in range (0,3):
    for coluna in range (0,3):
        if matriz[linha][coluna] % 2 == 0:
            par += matriz[linha][coluna]
print(f'A soma de todos os valores pares digitados é: {par}')

#Resolução da B:
for linha in range (0,3):
    for coluna in range (0,3):
        if coluna == 2:
            soma += matriz[linha][coluna]
print("=-"*30)
print(f'A soma dos valores da terceira coluna é: {soma}')

#Resolução da C:
for linha in range (0, 3):
    for coluna in range(0, 3):
        if linha == 1:
            if coluna == 0:
                maior = matriz[linha][coluna]
            elif matriz[linha][coluna] > maior:
                maior = matriz[linha][coluna]
print('=-'*30)
print(f'O maior valor da segunda linha é: {maior}')