# -*- coding: utf-8 -*-
"""ex085.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDSbryCMW7TeTNxhYVi5I_G1vSLctUy7
"""

'''
Crie um programa onde o usuário possa digitar sete valores numéricos e cadastre-os
em uma lista única que mantenha separados os valores pares e ímpares.
No final, mostre os valores pares e ímpares em ordem crescente.
'''

print("="*30)
print(f"{'LISTA PAR E IMPAR':^30}")
print("="*30)
print('\n\n\n')

junto = [[], []]

for c in range (1, 8):
    numero = int(input(f'Digite o {c}º número: '))
    if numero % 2 == 0:
        junto[0].append(numero)
    else:
        junto[1].append(numero)
junto[0].sort()
junto[1].sort()
print('=-'*30)
print(f'Os números pares são: {junto[0]}')
print(f'Os números ímpares são: {junto[1]}')