# -*- coding: utf-8 -*-
"""ex089.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jnh3vJ-XOG1JCGAE3js1PUkIeJ8sVO5
"""

'''
Crie um programa que leia nome e duas notas de vários alunos
e guarde tudo em uma lista composta.
No final, mostre um boletim contendo a média de cada um e permita que o usuário
possa mostrar as notas de cada aluno individualmente.
'''

print('='*30)
print(f"'{'Boletim com listas compostas':^30}'")
print("="*30)
print('\n\n\n')

ficha = []
while True:
    nome = str(input('Nome: '))
    nota1 = float(input('Nota 1: '))
    nota2 = float(input('Nota 2: '))
    media = (nota1 + nota2) / 2
    ficha.append([nome, [nota1, nota2], media])
    continua = str(input('Quer continuar? [S/N] ')).upper()
    print('-'*30)
    if continua in 'N':
        break
print('=-'*30)
print(f'{"No.":<4}{"NOME":<10}{"MÉDIA":>8}')
print('-'*26)
for i, a in enumerate(ficha):
    print(f'{i:<4}{a[0]:<10}{a[2]:>8.1f}')
while True:
    print('-'*35)
    opc = int(input('Mostrar notas de qual aluno? (999 interrompe): '))
    if opc == 999:
      print('Obrigado!')
      break
    if opc <= len(ficha) - 1:
        print(f'Notas de {ficha[opc][0]} são {ficha[opc][1]}')