# -*- coding: utf-8 -*-
"""ex082.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WE3QSx7WXoZCLDSwgEOJ2ZSRywKxAAhO
"""

'''
Crie um programa que vai ler vários números e colocar em uma lista.
Depois disso,
crie duas listas extras que vão conter apenas os valores pares e os valores ímpares digitados,
respectivamente. Ao final, mostre o conteúdo das três listas geradas.
'''

print('='*30)
print(f"{'Dividindo valores em várias lista':^30}")
print('='*30)
print('\n\n\n')

lista = []
par = []
impar = []

while True:
    numero = int(input("Digite um número: "))
    lista.append(numero)
    continua = str(input('Quer continuar? [S/N]: ')).strip().upper()[0]
    print('-'*30)
    if continua not in 'SN':
        print("Opção inválida.")
        continua = str(input('Quer continuar? [S/N]: ')).strip().upper()[0]
    if continua == 'N':
        break

#Lista geral:
print(f"Os valores digitados foram: {lista}")
#preenchendo listas par.
for c in lista:
    if c % 2 == 0:
        par.append(c)
print('=-'*15)
print(f"Os valores pares digitados foram: {par}")

#preenchendo listas impar.
for c in lista:
    if c % 2 == 1:
        impar.append(c)
print("=-"*15)
print(f"Os valores ímpares digitados foram: {impar}")