# -*- coding: utf-8 -*-
"""ex088.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTybuZUfxjqGx8gOc83BmfTjLfp2Whhn
"""

'''
Faça um programa que ajude um jogador da MEGA SENA a criar palpites.
O programa vai perguntar quantos jogos serão gerados e vai sortear
6 números entre 1 e 60 para cada jogo, cadastrando tudo em uma lista composta.
'''

print("="*30)
print(f"{'Palpites para a Mega Sena':^30}")
print("="*30)
print('\n\n\n')
from time import sleep
from random import randint

lista = [] #lista onde armazena 1 jogo
jogos = [] #lista onde armazena todos os jogos
quantidade = int(input("Quantos jogos você quer sortear? "))
total = 0
while total < quantidade: #primeiro laço onde trata a quantidade de jogos do usuário
    contador = 0
    while True: #preenche a lista sem números repetidos
        numero = randint(1, 60)
        if numero not in lista:
            lista.append(numero)
            contador += 1
        if contador >= 6:
            break
    lista.sort() # ordena as listas
    jogos.append(lista[:]) #insere listas em jogos
    lista.clear()
    total += 1
print('-='*3, f'Sorteando {quantidade} jogos', '=-'*3)

for indice, lista in enumerate(jogos): #organiza os prints dos jogos.
    print(f'Jogo {indice+1}: {lista}')
    sleep(1)
print(f"{'Boa sorte!':=^30}")