# -*- coding: utf-8 -*-
"""ex057.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYQGgExs6klg7DA7UYle07CCLMHb9m9k
"""

'''Faça um programa que leia o sexo de uma pessoa, mas só aceite os valores ‘M’ ou ‘F’.
Caso esteja errado, peça a digitação novamente até ter um valor correto.'''

print("="*30)
print("Validação de Dados")
print("="*30)
print("\n\n\n")


sexo = str(input('Digite o sexo [M/F]: ')).upper().strip()[0]
while sexo not in 'MF':
  sexo = str(input('Dados inválidos. Por favor, informe seu sexo: ')).upper().strip()[0]

print(f'Sexo {sexo} registrado')