# -*- coding: utf-8 -*-
"""ex058.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK98du1E8NAbkzzxAj0fHAUzetp_M73j
"""

'''Melhore o jogo do DESAFIO 28 onde o computador vai “pensar” em um número entre 0 e 10.
Só que agora o jogador vai tentar adivinhar até acertar,
mostrando no final quantos palpites foram necessários para vencer.'''

print("="*30)
print("Jogo da adivinhação 2.0")
print("="*30)

from random import randint


jogador = 0
computador = randint(0, 10)
palpites = 0
acertou = False

while not acertou:
    jogador = int(input("Digite um número de 0 a 10: "))
    if jogador == computador:
        acertou = True
    else:
      if jogador < computador:
        print("Mais...")
      elif jogador > computador:
        print("Menos...")
    palpites += 1
print(f"Número a ser adivinhado: {computador}")
print(f"Jogador acertou com {palpites} tentativas!")