# -*- coding: utf-8 -*-
"""ex059.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjrWibEZHdAcMkjBTZCF9ummuSwhcCSf
"""

'''Crie um programa que leia dois valores e mostre um menu na tela:

[ 1 ] somar
[ 2 ] multiplicar

[ 3 ] maior

[ 4 ] novos números

[ 5 ] sair do programa

Seu programa deverá realizar a operação solicitada em cada caso.'''

print("="*30)
print("Criando menu de opções.")
print("="*30)
print("\n\n\n")

numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))
opcao = 0


while opcao != 5:
  opcao = int(input('''Digite:
  [1] para somar
  [2] para multiplicar
  [3] maior número
  [4] novos números
  [5] sair do programa: '''))
  print('='*30)

  if opcao == 1:
    soma = numero1 + numero2
    print(f"A soma entre {numero1} e {numero2} é {soma}")
  elif opcao == 2:
    multiplicacao = numero1 * numero2
    print(f"A multiplicação entre {numero1} e {numero2} é {multiplicacao}")
  elif opcao == 3:
    if numero1 > numero2:
      print(f"O número {numero1} é maior que o número {numero2}")
    elif numero2 >numero1:
      print(f"O número {numero2} é maior que o número {numero1}")
    else:
      print("Os números são iguais.")
  elif opcao == 4:
    numero1 = int(input("Digite o primeiro número: "))
    numero2 = int(input("Digite o segundo número: "))
  elif opcao == 5:
    print("Finalizando...")
  else:
    print("Opção inválida. Tente novamente.")
print("Fim do programa.")