# -*- coding: utf-8 -*-
"""ex061.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyo-HPppR_aMuI_S_SMGbb-MWkLgZYPN
"""

'''Refaça o DESAFIO 51, lendo o primeiro termo e a razão de uma PA,
mostrando os 10 primeiros termos da progressão usando a estrutura while.'''

print('='*30)
print('Progressão Aritmética 2.0')
print('='*30)

numero = int(input('Digite o primeiro termo: '))
razao = int(input('Digite a razão: '))
termo = numero
contador = 1

while contador <= 10:
  print(f'{termo} -> ', end='')
  termo += razao
  contador += 1
print('FIM!')