# -*- coding: utf-8 -*-
"""ex069.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXqPcm63kb2hgDNqeecgzxA1Q57dNzBx
"""

'''Crie um programa que leia a idade e o sexo de várias pessoas.
A cada pessoa cadastrada, o programa deverá perguntar se o usuário quer ou não continuar.
No final, mostre:
A) quantas pessoas tem mais de 18 anos.
B) quantos homens foram cadastrados.
C) quantas mulheres tem menos de 20 anos.
'''

print('='*30)
print(f"{'Análise de dados do grupo':^30}")
print('='*30)

flag = ''
mais18 = homem = mulher20 = 0

while True:
  nome = str(input('Nome: ')).strip()
  idade = int(input('Idade: '))
  if idade >= 18:
    mais18 += 1
  sexo = str(input('Sexo [M/F]: ')).strip().upper()[0]
  if sexo not in 'MF':
    print('Opção inválida. Tente novamente.')
    sexo = str(input('Sexo [M/F]: ')).strip().upper()[0]
  if sexo == 'M':
    homem += 1
  if sexo == 'F' and idade < 20:
    mulher20 += 1
  flag = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
  if flag not in 'SN':
    print('Opção inválida. Tente novamente.')
    flag = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
  if flag == 'N':
    break

  print('-'*30)

print('FIM!!!')
print(f'Foram cadastradas {mais18} pessoas maiores de 18 anos.')
print(f'Foram cadastrados {homem} homens.')
print(f'Foram cadastrados {mulher20} mulheres menores de 20 anos.')