# -*- coding: utf-8 -*-
"""ex066.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoZDsczUwyTMFqbS9k0OooIFPFjn3kZ8
"""

'''Crie um programa que leia números inteiros pelo teclado.
O programa só vai parar quando o usuário digitar o valor 999, que é a condição de parada.
No final, mostre quantos números foram digitados
e qual foi a soma entre elas (desconsiderando o flag).
'''

print('='*30)
print('Vários números com flag')
print("="*30)
print('\n\n\n')

contador = soma = 0

while True:
  numero = int(input('Digite um número (999 para parar): '))
  print('-'*30)
  if numero != 999:
    contador += 1
    soma += numero
  if numero == 999:
    break
print(f'Foram registrados {contador} números')
print(f'A soma entre os números registrados é de {soma}')