# -*- coding: utf-8 -*-
"""ex062.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB1psIxA8fFdWTFsH7FrRniSw9MsAnR5
"""

'''Melhore o DESAFIO 61, perguntando para o usuário se ele quer mostrar mais alguns
termos.
O programa encerrará quando ele disser que quer mostrar 0 termos.'''

print("="*30)
print("Progressão Aritmética 3.0")
print('='*30)
print("\n\n\n")

numero = int(input('Digite o primeiro termo: '))
razao = int(input('Digite a razão: '))
termo = numero
contador = 1
total = 0
mais = 10

while mais != 0:
  total = total + mais
  while contador <= total:
    print(f'{termo} -> ', end='')
    termo += razao
    contador += 1
  print('Pausa!')
  mais = int(input("Qantos termos quer mostrar a mais? "))
  print('')
print("Fim!")