# -*- coding: utf-8 -*-
"""ex068.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Z4Y3s6RgU5A3iJiuCEELZClm60HYw62
"""

'''Faça um programa que jogue par ou ímpar com o computador.
O jogo só será interrompido quando o jogador perder,
mostrando o total de vitórias consecutivas que ele conquistou no final do jogo.'''

print('='*30)
print(f"{'jogo do Par ou Ímpar':^30}")
print('='*30)
print('\n\n\n')

from random import randint
vitorias = 0

selecionador = ''

while True:
  computador = randint(0, 10)
  selecionador = str(input('Par ou Ímpar? [P/I] ')).strip().upper()[0]
  while selecionador not in 'PI':
    print('Opção inválida.')
    selecionador = str(input('Par ou Ímpar? [P/I] ')).strip().upper()[0]
  jogador = int(input('Digite um número: '))
  print('-'*30)
  if (jogador + computador) % 2 == 0 and selecionador == 'P':
    print(f'Você jogou {jogador} e o computador {computador}, total: {jogador + computador}')
    print('Deu par!')
    print('Vitória.')
    print('-'*30)
    vitorias += 1
  elif (jogador + computador) % 2 == 1 and selecionador == 'I':
    print(f'Você jogou {jogador} e o computador {computador}, total: {jogador + computador}')
    print('Deu ímpar!')
    print('Vitória')
    print('-'*30)
    vitorias += 1
  elif (jogador + computador) %2 == 0 and selecionador == 'I':
    print(f'Você jogou {jogador} e o computador {computador}, total: {jogador + computador}')
    print('Deu par!')
    print('Derrota.')
    print('-'*30)
    break
  elif (jogador + computador) %2 == 1 and selecionador == 'P':
    print(f'Você jogou {jogador} e o computador {computador}, total: {jogador + computador}')
    print('Deu ímpar!')
    print('Derrota.')
    print('-'*30)
    break
print('='*30)
print(f"{'FIM DE JOGO!':^30}")
print(f"{f'Você venceu {vitorias} vezes.':^30}")
print('='*30)