# -*- coding: utf-8 -*-
"""ex063.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFSnrJCTLDT8AxuUnhY0B9jki4g9jTqp
"""

'''Escreva um programa que leia um número N inteiro qualquer e mostre na tela
os N primeiros elementos de uma Sequência de Fibonacci.'''

print("="*30)
print("Sequência de FIbonacci")
print("="*30)
print("\n\n\n")

numero = int(input("Quantos termos você quer mostrar? "))
termo1 = 0
termo2 = 1
print("{} -> {}".format(termo1, termo2), end=" ")
contador = 3
while contador <= numero:
    termo3 = termo1 + termo2
    print("-> {}".format(termo3), end=" ")
    termo1 = termo2
    termo2 = termo3
    contador += 1

print('Fim.')