# -*- coding: utf-8 -*-
"""ex067.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hmf0LtBfY8J_R1uKlVIi7VKZ3RIPOiwD
"""

'''Faça um programa que mostre a tabuada de vários números, um de cada vez,
para cada valor digitado pelo usuário.
O programa será interrompido quando o número solicitado for negativo.'''

print('='*30)
print(f"{'Tabuada 3.0':^30}")
print('='*30)

numero = 0
while True:
  numero = int(input('Digite um valor (qualquer número negativo para sair): '))
  if numero >= 0:
    for c in range (1, 11):
      print(f"{numero} x {c} = {numero * c}")
    print('='*30)
  if numero < 0:
    break
print('FIM!!!')