# -*- coding: utf-8 -*-
"""ex065.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpxdwSLa59hO1bffMhe7ylUl54Ma9kPz
"""

'''Crie um programa que leia vários números inteiros pelo teclado.
No final da execução, mostre a média entre todos os valores e qual foi o maior
e o menor valores lidos.
O programa deve perguntar ao usuário se ele quer ou não continuar a digitar valores.'''

print("="*30)
print("Maior e menor valor")
print("="*30)
print('\n\n\n')

contador = soma = maior = menor = 0
condicao = 'S'

while condicao in 'S':
    numero = int(input("Digite um número: "))
    condicao = str(input("Deseja continuar? [S/N] ")).upper().strip()
    print('-'*30)
    if condicao not in 'SN':
        print("Opção inválida!")
        condicao = str(input("Deseja continuar? [S/N] ")).upper().strip()
        print('-'*30)
    contador += 1
    soma += numero
    if contador == 1:
        maior = menor = numero
    else:
        if numero > maior:
            maior = numero
        if numero < menor:
            menor = numero
print(f'A média dos valores digitados é de {soma/contador:.2f}')
print(f"O maior número digitado foi: {maior}")
print(f"O menor número digitado foi: {menor}")