# -*- coding: utf-8 -*-
"""ex060.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQrP2qch2iDcrNOCWpmIxnu0OCq7SWmJ
"""

'''Faça um programa que leia um número qualquer e mostre o seu fatorial. Exemplo:

5! = 5 x 4 x 3 x 2 x 1 = 120'''

print("="*30)
print("Cálculo de Fatorial.")
print("="*30)
print("\n\n\n")


numero = int(input('Digite um número para calcular seu fatorial: '))
contador = numero
fatorial = 1
print(f"Calculando {numero}! = " , end='')
while contador > 0:
  print(f'{contador}',end='' )
  print(' x ' if contador > 1 else ' = ', end='')
  fatorial *= contador
  contador -= 1
print(f'{fatorial}')