# -*- coding: utf-8 -*-
"""ex064.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5xiIN0rRQgg0SDTqUuphcJsJpQMlrZd
"""

'''Crie um programa que leia vários números inteiros pelo teclado.
O programa só vai parar quando o usuário digitar o valor 999, que é a condição de parada.
No final, mostre quantos números foram digitados e qual foi a soma entre eles
(desconsiderando o flag).'''

print("="*30)
print("Valores 1.0")
print("="*30)

contador = numero = soma = 0
while numero != 999:
  numero = int(input("Digite um número: "))
  print('-'*30)
  if numero != 999:
    contador += 1
    soma += numero

print(f"Foram registrados {contador} números.")
print(f"E a soma entre eles é de: {soma}")