# -*- coding: utf-8 -*-
"""ex070.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOXvQxXwSowh3iE0-G7Q-Fqn-toqMdE9
"""

'''Crie um programa que leia o nome e o preço de vários produtos.
O programa deverá perguntar se o usuário vai continuar ou não.
No final, mostre:
A) qual é o total gasto na compra.

B) quantos produtos custam mais de R$1000.

C) qual é o nome do produto mais barato.

'''


print('='*30)
print(f"{'Estatísticas em produtos.':^30}")
print('='*30)

total = 0
mais1000 = 0
mais_barato = 0
item_barato = ' '
while True:
  produto = str(input('Nome do produto: '))
  preco = float(input('Preço: R$'))
  total += preco
  if preco > 1000:
    mais1000 += 1
  mais_barato = preco
  item_barato = produto
  if preco < mais_barato:
    mais_barato = preco
    item_barato = produto

  continuar = ' '
  continuar = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
  print('-'*30)
  if continuar == 'N':
    break
  while continuar not in 'SN':
    print('Opção inválida.')
    continuar = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
print('='*30)
print(f'O total da compra foi R${total:.2f}')
print(f'Temos {mais1000} produtos custando mais de R$1000.00')
print(f'O produto mais barato foi o {item_barato} que custa R${mais_barato:.2f}')