# -*- coding: utf-8 -*-
"""ex002

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEZmx4h_jqx33WJEa8SrmCyw3DMUKfke
"""

nome = input("Digite seu nome: ")
print("Olá {}! Bem vindo ao mundo python!".format(nome))