# -*- coding: utf-8 -*-
"""ex001

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBzKbUJRSCjMJVgD3NfotFKOcSAZSHNq
"""

print("Hello Python")