# -*- coding: utf-8 -*-
"""ex039

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMLH1ygIOMs3TWfb_Q2LHQv9jsi9QHxj
"""

# Faça um programa que leia o ano de nascimento de um jovem e informe,
#de acordo com a sua idade, se ele ainda vai se alistar ao serviço militar,
#se é a hora exata de se alistar ou se já passou do tempo do alistamento.
#Seu programa também deverá mostrar o tempo que falta ou que passou do prazo.

print("="*30)
print(" "*3,"ALISTAMENTO MILITAR")
print("="*30)
print("\n\n\n")

from datetime import date
ano_atual = date.today().year
ano_nascimento = int(input("Digite o ano de nascimento: "))
idade = ano_atual - ano_nascimento
print(f"Quem nasceu em {ano_nascimento} tem {idade} anos em {ano_atual}.")
if idade == 18:
    print("Você tem que se alistar IMEDIATAMENTE!")
elif idade < 18:
    saldo = 18 - idade
    print(f"Ainda falta {saldo} anos para o alistamento.")
    print(f"Seu alistamento será em {ano_atual + saldo}.")
else:
    saldo = idade - 18
    print(f"Você já deveria ter se alistado há {saldo} anos.")