# -*- coding: utf-8 -*-
"""ex036

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_uvdvl7F2PIbOMc3ZzA7wQd1ShHYx97
"""

#Escreva um programa para aprovar o empréstimo bancário para a compra de uma casa.
#Pergunte o valor da casa, o salário do comprador e em quantos anos ele vai pagar.
#A prestação mensal não pode exceder 30% do salário ou então o empréstimo será negado.
print("="*30)
print("=== Aprovando Empréstimo ===")
print("="*30)
print('\n\n\n')

ValorCasa = float(input('Qual o valor da casa? R$'))
Salario = float(input('Qual o seu salário? R$'))
Financiamento = float(input('Em quantos anos pretende pagar? '))


ValorParcela = ValorCasa / (Financiamento * 12)

PorcentagemSalário = Salario * 30 / 100

if ValorParcela > PorcentagemSalário:
    print(f'Seu salário é de {Salario} e 30% dele corresponde a {PorcentagemSalário:.2f}.')
    print(f'A parcela ficaria em {ValorParcela:.2f}')
    print('Empréstimo negado!')
else:
  print(f'Seu salário é de {Salario} e 30% dele corresponde a {PorcentagemSalário:.2f}.')
  print(f'A parcela ficaria em {ValorParcela:.2f}')
  print('Empréstimo aprovado!')