# -*- coding: utf-8 -*-
"""ex038

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17oEwcJSR3ks4gHSaYYYekQRzTS_gHY1m
"""

#Escreva um programa que leia dois números inteiros e compare-os. mostrando na tela uma mensagem:
#O primeiro valor é maior
#O segundo valor é maior
#Os números são iguais

print("="*30)
print("=== Comparador de números ===")
print("="*30)
print('\n\n\n')

numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))

if numero1 > numero2:
    print("O primeiro valor é maior")
elif numero2 > numero1:
    print("O segundo valor é maior")
else:
    print("Os números são iguais")