# -*- coding: utf-8 -*-
"""ex037

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lno7p_rAhH65_cDiN4eETR-JisouKrxr
"""

#Escreva um programa em Python que leia um número inteiro qualquer e peça para
#o usuário escolher qual será a base de conversão: 1 para binário, 2 para octal e 3 para hexadecimal.

print("="*30)
print('=== Conversor de Bases numéricas ===')
print("="*30)
print('\n\n')

numero = int(input('Digite um número inteiro: '))
escolha = int(input('''Escolha uma das bases para conversão:
[1] converter para BINÁRIO
[2] converter para OCTAL
[3] converter para HEXADECIMAL
Sua escolha: '''))
if escolha == 1:
    print(f'O número {numero} convertido para BINÁRIO é {bin(numero)[2:]}')

elif escolha == 2:
    print(f'O número {numero} convertido para OCTAL é {oct(numero)[2:]}')

else:
    print(f'O número {numero} convertido para HEXADECIMAL é {hex(numero)[2:]}')