# -*- coding: utf-8 -*-
"""ex040

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yev0Mic-yQa7S9NY3Wo0g9b9Jrq7jB4I
"""

#Crie um programa que leia duas notas de um aluno e calcule sua média, mostrando uma mensagem no final, de acordo com a média atingida:
#Média abaixo de 5.0: REPROVADO
#Média entre 5.0 e 6.9: RECUPERAÇÃO
#Média 7.0 ou superior: APROVADO

print("="*30)
print("=== Calculadora de Média ===")
print("="*30)
print('\n\n\n')
nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))

media = (nota1 + nota2) / 2

print(f'\nA média do aluno é {media:.2f}')

if media >= 7:
  print('Aprovado!!!')
elif media >= 5 and media < 7:
  print('Recuperação!!!')
else:
  print('Reprovado!!!')