# -*- coding: utf-8 -*-
"""ex043

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T04FdmkJ4BJJcLsOAJyDXkePMM-h-XyA
"""

#Desenvolva uma lógica que leia o peso e a altura de uma pessoa, calcule seu Índice de Massa Corporal (IMC) e mostre seu status, de acordo com a tabela abaixo:
#IMC abaixo de 18,5: Abaixo do Peso
#Entre 18,5 e 25: Peso Ideal
#25 até 30: Sobrepeso
#30 até 40: Obesidade
#Acima de 40: Obesidade Mórbida

print("="*40)
print("Calculadora de IMC")
print("="*40)
print('\n\n\n')

altura = float(input("Digite sua altura: "))
peso = float(input("Digite seu peso: "))

imc = peso / (altura**2)

if imc < 18.5:
  print(f'Seu IMC é de {imc:.1f}: Abaixo do peso ideal.')
elif imc >=18.5 and imc <= 25:
  print(f' Seu IMC é de {imc:.1f}: Peso Ideal')
elif imc > 25 and imc <= 30:
  print(f'Seu IMC é de {imc:.1f}: Sobrepeso')
elif imc > 30 and imc <= 40:
  print(f'Seu IMC é de{imc:.1f}: Obesidade')
else:
  print(f'Seu IMC é de {imc:.1f}: Obesidade Morbida')