# -*- coding: utf-8 -*-
"""ex044

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7n6uJ8y1D2sSdlXzUU2R0Q6pCVZtHXt
"""

#Elabore um programa que calcule o valor a ser pago por um produto, considerando o seu preço normal e condição de pagamento:
#à vista dinheiro/cheque: 10% de desconto
#à vista no cartão: 5% de desconto
#em até 2x no cartão: preço formal
#3x ou mais no cartão: 20% de juros

print('='*40)
print('Gerenciador de pagamento')
print('='*40)
print('\n\n\n')

valor = float(input('Digite o valor do produto: R$'))
print(' ')
opcao = int(input('''Digite a opção de pagamento:
[1]À vista (dinheiro o cheque)
[2]À vista no cartão de crédito
[3]Em até 2x no cartão de crédito
[4]3x ou mais no cartão de crédito: '''))
print(' ')
if opcao == 1:
  desconto = valor - (valor * 10 / 100)
  print(f'O valor a ser pago é de R${desconto:.2f}')
elif opcao == 2:
  desconto = valor - (valor * 5 / 100)
  print(f'O valor a ser pago é de R${desconto:.2f}')
elif opcao == 3:
  parcela = valor / 2
  print(f'O valor a ser pago é de R${valor:.2f} em 2x de R${parcela:.2f}')
elif opcao == 4:
  juros = valor + (valor * 20 / 100)
  parcela = int(input('Quantas parcelas? '))
  if parcela > 2:
    valor_parcela = juros / parcela
    print(f'O valor fica em R${juros:.2f} em {parcela}x de R${valor_parcela}')
  else:
    print('Só pode ser dividido em mais que 2 parcelas.')
else:
  print('Opção inválida de pagamento.')