# -*- coding: utf-8 -*-
"""ex041

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkIGqGu06m4aNPU1MtgLy7Hjv20zmD8m
"""

#A Confederação Nacional de Natação precisa de um programa que leia o ano de nascimento de um atleta e mostre sua categoria, de acordo com a idade:
#Até 9 anos: MIRIM
#Até 14 anos: INFANTIL
#Até 19 anos: JÚNIOR
#Até 25 anos: SÊNIOR
#Acima de 25 anos: MASTER

print('='*30)
print('Confederação Nacional de Natação')
print('='*30)
print("\n\n\n")
from datetime import date

nome = str(input('Digite o nome do atleta: '))
ano = int(input('Digite o ano de nascimento do atleta: '))
idade = date.today().year - ano


if idade <= 9:
  print(f'O atleta {nome} tem {idade} anos e irá competir na categoria MIRIM.')
elif idade >=10 and idade <=14:
  print(f'O atleta {nome} tem {idade} anos e irá competir na categoria INFANTIL.')
elif idade >=15 and idade <= 18:
  print(f'O atleta {nome} tem {idade} anos e irá competir na categoria JÚNIOR.')
elif idade >=19 and idade <= 25:
  print(f'O atleta {nome} tem {idade} anos e irá competir na categoria SÊNIOR.')
else:
  print(f'O atleta {nome} tem {idade} anos e irá competir na categoria MASTER.')