# -*- coding: utf-8 -*-
"""ex042

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VP4TLIxpNnO6bbpe854n3ySF6Hj8NH0E
"""

#Refaça o DESAFIO 35 dos triângulos, acrescentando o recurso de mostrar que tipo de triângulo será formado:
#EQUILÁTERO: todos os lados iguais
#ISÓSCELES: dois lados iguais, um diferente
#ESCALENO: todos os lados diferentes

print('='*40)
print("=-=-= Analisando Triângulos =-=-=")
print('='*40)
print('\n\n\n')

r1 = float(input('Digite o comprimento da primeira reta: '))
r2 = float(input('Digite o comprimento da segunda reta: '))
r3 = float(input('Digite o comprimento da terceira reta: '))

#verificando se forma um triângulo
if r1 < r2 + r3 and r2 < r1 + r3 and r3 < r1 + r2:
  print('Essas retas podem formar um triângulo!')
  #verifica qual tipo de triângulo é formado.
  if r1 == r2 == r3:
    print('Essas medidas forma um triângulo EQUILÁTERO!')
  elif r1 == r2 or r1 == r3 or r2 == r3:
    print('Essas medidas formam um triângulo ISÓSCELES!')
  else:
    print('Essas medidas forma um triângulo ESCALENO')
else:
  print('Essas retas não podem formar um triângulo!')